In [34]:
import pandas as pd
import numpy as np

In [35]:
train = pd.read_csv('train_final.csv')
print(train[train.is_churn == 1].shape)
print(train[train.is_churn == 0].shape)
train.head()

(3000, 2)
(3000, 2)

                                           msno  is_churn
0  f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=         1
1  zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=         1
2  K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=         1
3  ibIHVYBqxGwrSExE63/omeDD99M5vYB3CN2HzkEY+eM=         1
4  moRTKhKIDvb+C8ZHOgmaF4dXMLk0jOn65d7a8tQ2Eds=         1

### LINEAR MODELS

In [36]:
members_lin = pd.read_csv('members_linear6000.csv')
logs_lin = pd.read_csv('transactions_linear6000.csv')
trans_lin = pd.read_csv('logs_linear6000.csv')

In [37]:
unique_ids = members_lin.msno.unique()

In [38]:
train = train[train.msno.isin(unique_ids)]

In [39]:
lin1 = pd.merge(members_lin, logs_lin, on='msno')

In [40]:
lin2 = pd.merge(lin1, trans_lin, on='msno')

In [41]:
lin_final = pd.merge(lin2, train, on='msno')

In [42]:
lin_final.to_csv('linear_model6000.csv', index=False)

In [43]:
print(lin_final.shape)
lin_final.head()

(6000, 181)

,msno,bd,city_1,city_3,city_4,city_5,city_6,city_7,city_8,city_9,...,min_days_diff,most_popular_days_1,most_popular_days_2,most_popular_days_3,least_popular_days_1,least_popular_days_2,least_popular_days_3,most_popular_season_2,least_popular_season_2,is_churn
0,7Bx3zw0JFFwCXjkWgqhMxnQQLzy7Idmc+J1qXU8GhAY=,25,0,0,0,0,0,0,0,0,...,2.0,0,0,1,1,0,0,1,1,1
1,OFhJwMVNuJKYC6MNLmCulVSJatkQ1ZexipKpyujQa4c=,28,0,0,0,1,0,0,0,0,...,2.0,0,0,1,1,0,0,1,1,0
2,OFjgd4O5aCzXBFosKhGhqB8bKEgtV/9RQSN28yPtGHk=,28,1,0,0,0,0,0,0,0,...,0.0,0,0,1,1,0,0,1,1,0
3,G7Zl2XAspwOaYJLlKK3FLmgypn3qYeGFKC/9WbczS+0=,43,0,0,1,0,0,0,0,0,...,14.0,0,0,1,1,0,0,1,1,1
4,7v4BtQAEWazr9JYq5iqbNtWp0SNTNgKTBNZ0z+9CGEM=,21,0,0,0,0,0,0,0,0,...,0.0,0,0,1,1,0,0,1,1,1

In [44]:
for i in lin_final.columns:
    print(i)

msno
bd
city_1
city_3
city_4
city_5
city_6
city_7
city_8
city_9
city_10
city_11
city_12
city_13
city_14
city_15
city_16
city_17
city_18
city_19
city_20
city_21
city_22
gender_female
gender_male
registered_via_3
registered_via_4
registered_via_7
registered_via_9
registered_via_13
season_1
season_2
season_3
season_4
days_1
days_2
days_3
num_of_transactions
extra_payment_plans_total
extra_payment_plans_count
avg_plan_list_price
avg_actual_amount_paid
is_auto_renew_total
is_cancel_total
left_payment_seconds_total
avg_transaction_days_diff
max_transaction_days_diff
min_transaction_days_diff
avg_expire_days_diff
max_expire_days_diff
min_expire_days_diff
most_popular_payment_id_10
most_popular_payment_id_12
most_popular_payment_id_13
most_popular_payment_id_14
most_popular_payment_id_15
most_popular_payment_id_16
most_popular_payment_id_17
most_popular_payment_id_18
most_popular_payment_id_19
most_popular_payment_id_20
most_popular_payment_id_21
most_popular_payment_id_22
most_popular_payment_id_23
most_popular_payment_id_26
most_popular_payment_id_27
most_popular_payment_id_28
most_popular_payment_id_29
most_popular_payment_id_30
most_popular_payment_id_31
most_popular_payment_id_32
most_popular_payment_id_33
most_popular_payment_id_34
most_popular_payment_id_35
most_popular_payment_id_36
most_popular_payment_id_37
most_popular_payment_id_38
most_popular_payment_id_39
most_popular_payment_id_40
most_popular_payment_id_41
most_popular_transaction_days_1
most_popular_transaction_days_2
most_popular_transaction_days_3
least_popular_transaction_days_1
least_popular_transaction_days_2
least_popular_transaction_days_3
most_popular_transaction_season_1
most_popular_transaction_season_2
most_popular_transaction_season_3
most_popular_transaction_season_4
least_popular_transaction_season_1
least_popular_transaction_season_2
least_popular_transaction_season_3
least_popular_transaction_season_4
most_popular_expire_days_1
most_popular_expire_days_2
most_popular_expire_days_3
least_popular_expire_days_1
least_popular_expire_days_2
least_popular_expire_days_3
most_popular_expire_season_1
most_popular_expire_season_2
most_popular_expire_season_3
most_popular_expire_season_4
least_popular_expire_season_1
least_popular_expire_season_2
least_popular_expire_season_3
least_popular_expire_season_4
payment_id_is_always_auto_renew_10True
payment_id_is_always_auto_renew_12False
payment_id_is_always_auto_renew_13False
payment_id_is_always_auto_renew_14True
payment_id_is_always_auto_renew_15False
payment_id_is_always_auto_renew_16False
payment_id_is_always_auto_renew_16True
payment_id_is_always_auto_renew_17False
payment_id_is_always_auto_renew_18True
payment_id_is_always_auto_renew_19True
payment_id_is_always_auto_renew_20False
payment_id_is_always_auto_renew_21True
payment_id_is_always_auto_renew_22False
payment_id_is_always_auto_renew_23True
payment_id_is_always_auto_renew_26False
payment_id_is_always_auto_renew_27False
payment_id_is_always_auto_renew_27True
payment_id_is_always_auto_renew_28False
payment_id_is_always_auto_renew_29False
payment_id_is_always_auto_renew_29True
payment_id_is_always_auto_renew_30False
payment_id_is_always_auto_renew_30True
payment_id_is_always_auto_renew_31False
payment_id_is_always_auto_renew_31True
payment_id_is_always_auto_renew_32False
payment_id_is_always_auto_renew_33False
payment_id_is_always_auto_renew_33True
payment_id_is_always_auto_renew_34False
payment_id_is_always_auto_renew_34True
payment_id_is_always_auto_renew_35False
payment_id_is_always_auto_renew_36False
payment_id_is_always_auto_renew_36True
payment_id_is_always_auto_renew_37False
payment_id_is_always_auto_renew_37True
payment_id_is_always_auto_renew_38False
payment_id_is_always_auto_renew_39False
payment_id_is_always_auto_renew_39True
payment_id_is_always_auto_renew_40False
payment_id_is_always_auto_renew_40True
payment_id_is_always_auto_renew_41False
payment_id_is_always_auto_renew_41True
num_of_logs
sum_num25
avg_num25
sum_num50
avg_num50
sum_num75
avg_num75
sum_num985
avg_num985
sum_num100
avg_num100
sum_num_unq
avg_num_unq
sum_total_secs
avg_total_secs
sum_total_songs
avg_total_songs
perc_of_accidentally_songs
perc_of_favourite_songs
avg_songs_per_month
avg_days_diff
max_days_diff
min_days_diff
most_popular_days_1
most_popular_days_2
most_popular_days_3
least_popular_days_1
least_popular_days_2
least_popular_days_3
most_popular_season_2
least_popular_season_2
is_churn

### XGBOOST MODELS

In [45]:
members_xg = pd.read_csv('members_boost6000.csv')
logs_xg = pd.read_csv('logs_trees6000.csv')
trans_xg = pd.read_csv('transactions_trees6000.csv')

In [46]:
xg1 = pd.merge(members_xg, logs_xg, on='msno')

In [47]:
xg2 = pd.merge(xg1, trans_xg, on='msno')

In [48]:
xg_final = pd.merge(xg2, train, on='msno')

In [49]:
print(xg_final.shape)
xg_final.head()

(6000, 59)

,msno,city,bd,gender,registered_via,days,season,num_of_logs,sum_num25,avg_num25,...,most_popular_transaction_days,least_popular_transaction_days,most_popular_transaction_season,least_popular_transaction_season,most_popular_expire_days,least_popular_expire_days,most_popular_expire_season,least_popular_expire_season,payment_id_is_always_auto_renew,is_churn
0,7Bx3zw0JFFwCXjkWgqhMxnQQLzy7Idmc+J1qXU8GhAY=,13,25.0,female,9,3,4,30,100,3.333333,...,3,3,2,2,3,3,2,2,41True,1
1,OFhJwMVNuJKYC6MNLmCulVSJatkQ1ZexipKpyujQa4c=,5,NaN,female,9,3,4,21,136,6.476190,...,1,1,2,2,1,1,2,2,40True,0
2,OFjgd4O5aCzXBFosKhGhqB8bKEgtV/9RQSN28yPtGHk=,1,NaN,NaN,7,2,1,18,34,1.888889,...,2,2,2,2,2,2,3,3,38False,0
3,G7Zl2XAspwOaYJLlKK3FLmgypn3qYeGFKC/9WbczS+0=,4,43.0,female,7,3,2,5,18,3.600000,...,3,3,2,2,1,1,4,4,32False,1
4,7v4BtQAEWazr9JYq5iqbNtWp0SNTNgKTBNZ0z+9CGEM=,15,21.0,female,3,3,2,25,388,15.520000,...,1,1,2,2,2,2,3,3,28False,1

In [50]:
xg_final.to_csv('xgboost_model6000.csv', index=False)

In [51]:
for i in xg_final.columns:
    print(i)

msno
city
bd
gender
registered_via
days
season
num_of_logs
sum_num25
avg_num25
sum_num50
avg_num50
sum_num75
avg_num75
sum_num985
avg_num985
sum_num100
avg_num100
sum_num_unq
avg_num_unq
sum_total_secs
avg_total_secs
sum_total_songs
avg_total_songs
perc_of_accidentally_songs
perc_of_favourite_songs
avg_songs_per_month
avg_days_diff
max_days_diff
min_days_diff
most_popular_days
least_popular_days
most_popular_season
least_popular_season
num_of_transactions
most_popular_payment_id
extra_payment_plans_total
extra_payment_plans_count
avg_plan_list_price
avg_actual_amount_paid
is_auto_renew_total
is_cancel_total
left_payment_seconds_total
avg_transaction_days_diff
max_transaction_days_diff
min_transaction_days_diff
avg_expire_days_diff
max_expire_days_diff
min_expire_days_diff
most_popular_transaction_days
least_popular_transaction_days
most_popular_transaction_season
least_popular_transaction_season
most_popular_expire_days
least_popular_expire_days
most_popular_expire_season
least_popular_expire_season
payment_id_is_always_auto_renew
is_churn

### TREE MODELS

In [52]:
members_tree = pd.read_csv('members_trees6000.csv')
logs_xg = pd.read_csv('logs_trees6000.csv')
trans_xg = pd.read_csv('transactions_trees6000.csv')

In [53]:
tree1 = pd.merge(members_tree, logs_xg, on='msno')

In [54]:
tree2 = pd.merge(tree1, logs_xg, on='msno')

In [55]:
tree_final = pd.merge(tree2, train, on='msno')

In [56]:
print(tree_final.shape)
tree_final.head()

(6000, 62)

,msno,city,bd,gender,registered_via,days,season,num_of_logs_x,sum_num25_x,avg_num25_x,...,perc_of_favourite_songs_y,avg_songs_per_month_y,avg_days_diff_y,max_days_diff_y,min_days_diff_y,most_popular_days_y,least_popular_days_y,most_popular_season_y,least_popular_season_y,is_churn
0,7Bx3zw0JFFwCXjkWgqhMxnQQLzy7Idmc+J1qXU8GhAY=,13,25,female,9,3,4,30,100,3.333333,...,0.818006,1033.0,22.533333,58.0,2.0,3,1,2,2,1
1,OFhJwMVNuJKYC6MNLmCulVSJatkQ1ZexipKpyujQa4c=,5,-1,female,9,3,4,21,136,6.476190,...,0.815591,1193.0,26.571429,52.0,2.0,3,1,2,2,0
2,OFjgd4O5aCzXBFosKhGhqB8bKEgtV/9RQSN28yPtGHk=,1,-1,NaN,7,2,1,18,34,1.888889,...,0.889381,452.0,20.000000,52.0,0.0,3,1,2,2,0
3,G7Zl2XAspwOaYJLlKK3FLmgypn3qYeGFKC/9WbczS+0=,4,43,female,7,3,2,5,18,3.600000,...,0.530612,49.0,28.400000,46.0,14.0,3,1,2,2,1
4,7v4BtQAEWazr9JYq5iqbNtWp0SNTNgKTBNZ0z+9CGEM=,15,21,female,3,3,2,25,388,15.520000,...,0.563173,1021.0,16.720000,42.0,0.0,3,1,2,2,1

In [57]:
tree_final.to_csv('trees_model6000.csv', index=False)

In [58]:
for i in tree_final.columns:
    print(i)

msno
city
bd
gender
registered_via
days
season
num_of_logs_x
sum_num25_x
avg_num25_x
sum_num50_x
avg_num50_x
sum_num75_x
avg_num75_x
sum_num985_x
avg_num985_x
sum_num100_x
avg_num100_x
sum_num_unq_x
avg_num_unq_x
sum_total_secs_x
avg_total_secs_x
sum_total_songs_x
avg_total_songs_x
perc_of_accidentally_songs_x
perc_of_favourite_songs_x
avg_songs_per_month_x
avg_days_diff_x
max_days_diff_x
min_days_diff_x
most_popular_days_x
least_popular_days_x
most_popular_season_x
least_popular_season_x
num_of_logs_y
sum_num25_y
avg_num25_y
sum_num50_y
avg_num50_y
sum_num75_y
avg_num75_y
sum_num985_y
avg_num985_y
sum_num100_y
avg_num100_y
sum_num_unq_y
avg_num_unq_y
sum_total_secs_y
avg_total_secs_y
sum_total_songs_y
avg_total_songs_y
perc_of_accidentally_songs_y
perc_of_favourite_songs_y
avg_songs_per_month_y
avg_days_diff_y
max_days_diff_y
min_days_diff_y
most_popular_days_y
least_popular_days_y
most_popular_season_y
least_popular_season_y
is_churn

In [59]:
train[train.is_churn == 1].shape

(3000, 2)

In [60]:
train[train.is_churn == 0].shape

(3000, 2)